"""Render the shared catalogue as ``docs/events.md``, the page every team reads.

    python -m ecsctx.contrib.ottu.render_docs [path]

A developer choosing an event, and a reviewer checking the choice, need one
place that lists every shared event with when to log it — not eleven modules
to open. The page is generated so it cannot drift from the code; a test fails
when the committed copy is stale.
"""

import importlib
import sys
from pathlib import Path

from ecsctx.contrib.ottu import ALL_DOMAINS
from ecsctx.events.spec import EventSpec

HEADER = """\
<!-- Generated by `python -m ecsctx.contrib.ottu.render_docs`. Do not edit. -->

# Ottu log events

The shared vocabulary every Ottu service logs with. Import the constant and
pass its payload; never type the action:

```python
from ecsctx.contrib.ottu.net import OutboundFailure
from ecsctx.contrib.ottu.pg import PG_REQUEST_FAILED
from ecsctx.events import Outcome

logger.warning(
    "PSP rejected the call",
    ecs_event=PG_REQUEST_FAILED.ecs(
        outcome=Outcome.FAILURE, reason=OutboundFailure.HTTP_CLIENT_ERROR
    ),
)
```

Look here before adding an event. A service's own events live in one module
of that service and follow the same naming rules; an event a second service
needs, or a new reason for a shared event, is added here by PR. See
[the rule every service follows](rules/log-events.md).
"""


def _module(domain: str):
    return importlib.import_module(f"ecsctx.contrib.ottu.{domain}")


def _constant(module, spec: EventSpec) -> str:
    return next(
        name for name, value in vars(module).items() if value is spec and name.isupper()
    )


def _summary(module) -> str:
    # "Shared ``pg.*`` domain: the PSP boundary only." -> "The PSP boundary only."
    first = (module.__doc__ or "").strip().splitlines()[0].replace("``", "`")
    covers = first.partition(" domain: ")[2] or first
    return covers[:1].upper() + covers[1:]


def _codes(values) -> str:
    return ", ".join(f"`{value}`" for value in values)


def _event(module, spec: EventSpec) -> list[str]:
    lines = [
        f"### `{spec.action}`",
        "",
        f"`from {module.__name__} import {_constant(module, spec)}`",
        "",
        spec.description,
        "",
    ]
    if spec.terminal:
        lines.append(
            f"- **Level:** {spec.level}; on failure {spec.level_on_failure}. "
            f"Terminal: `.ecs()` needs an outcome."
        )
    else:
        lines.append(f"- **Level:** {spec.level}. Not terminal: no outcome.")
    ecs = [f"kind `{spec.kind}`"]
    if spec.category:
        ecs.append(f"category {_codes(spec.category)}")
    if spec.type:
        ecs.append(f"type {_codes(spec.type)}")
    lines.append(f"- **ECS:** {', '.join(ecs)}")
    if spec.reasons:
        reason_class = type(spec.reasons[0])
        lines.append(
            f"- **Reasons:** `{reason_class.__name__}` "
            f"(`from {reason_class.__module__} import {reason_class.__name__}`): "
            f"{_codes(spec.reasons)}"
        )
    if spec.required:
        lines.append(f"- **Carries:** {_codes(spec.required)}")
    if spec.optional:
        lines.append(f"- **May carry:** {_codes(spec.optional)}")
    lines.append("")
    return lines


def render() -> str:
    domains = sorted(ALL_DOMAINS)
    lines = [HEADER, "| Domain | Events | Covers |", "|---|---|---|"]
    for domain in domains:
        lines.append(
            f"| [`{domain}`](#{domain}) | {len(ALL_DOMAINS[domain])} | "
            f"{_summary(_module(domain))} |"
        )
    lines.append("")
    for domain in domains:
        module = _module(domain)
        lines += [f"## `{domain}`", "", _summary(module), ""]
        for spec in sorted(ALL_DOMAINS[domain], key=lambda s: s.action):
            lines += _event(module, spec)
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: list[str]) -> None:
    target = Path(argv[1] if len(argv) > 1 else "docs/events.md")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render())


if __name__ == "__main__":
    main(sys.argv)
